### ISSUE TITLE
Fails with "Error in reloc table!"

### ISSUE THREAD

**Issue by hippietrail** [emoon/AmigaHunkParser#5]
After the endian detection was fixed I got the program to compile and tested it on the one ancient Amiga program I have but just got this error
```
Error in reloc table!
```
I don't have any Amiga stuff anymore so I looked for some old executable files. I chose this hello world example from Fish Disk number 1: https://ftp.funet.fi/pub/amiga/fish/001-100/ff001/hello.lha

**Comment by emoon** [comment]
Unsure what could cause this. I haven't used this code for a very long time.

**Comment by hippietrail** [comment]
No worries. I'm writing my own Amiga Hunks parser and comparing to old projects I can find.

**Comment by emoon** [comment]
Cool. Hopefully the code can help as some reference at least.
